[State]
LastPostedFoundTime = 2023-03-01T09:29:51+10:00

[Configuration]
SOCKS5ProxyURL = ''
GeocachingAPIURL = 'https://www.geocaching.com'

[SearchTerms]
Latitude = -27.46794
Longitude = 153.02809
RadiusMeters = 16000
AreaName = 'Brisbane'
