[Configuration]
HTTPProxyURL = ''
GeocachingAPIURL = 'https://www.geocaching.com'

[SearchTerms]
Latitude = -27.46794
Longitude = 153.02809
RadiusMeters = 16000
AreaName = 'Brisbane'
IgnorePremium = true
